# Generated by Django 5.1 on 2024-09-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrtresource',
            name='url',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
