# Generated by Django 5.1 on 2024-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='origin_stations', to='mrt_app.station'),
        ),
        migrations.DeleteModel(
            name='AdjacencyStation',
        ),
    ]
