# Generated by Django 5.1 on 2024-08-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('destination_sattion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_stations', to='mrt_app.station')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_stations', to='mrt_app.station')),
            ],
        ),
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.IntegerField()),
                ('stop_time', models.IntegerField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='mrt_app.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='mrt_app.station')),
            ],
        ),
    ]
