# Generated by Django 5.1 on 2024-09-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrt_app', '0002_alter_mrtresource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrtresource',
            name='is_save_to_mongodb',
            field=models.BooleanField(default=False),
        ),
    ]
