# Generated by Django 5.1 on 2024-08-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrt_app', '0002_station_destinations_delete_adjacencystation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('origin_station', models.CharField(max_length=30)),
                ('destination_station', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
