# Generated by Django 5.1 on 2024-08-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrt_app', '0002_origindestination_traveltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacencyStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=1)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_station', to='mrt_app.station')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_station', to='mrt_app.station')),
            ],
        ),
    ]
